- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_setup

    - name: create vprofice VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpc_cider}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpc_out
    - debug:
        var: vpc_out
    - name: Create public subnet 1 in zone 1
      ec2_vpc_subnet: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{PubSub1Cidr}}"
        map_public: yes
        resourse_tags:
          Name: vprofile-pubsub1
        register: PubSub1Cidr
    - debug:
        var: PubSub1Cidr


