---
- name: setup vprofile stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: vpc setup variable
      include_vars: vars/output_vars
    - name: import vpro-ami
      include_vars: vars/vprostacksetup
    - name: Create vprofile ec2 key
      ec2_key:
        name: vprokey
        region: "{{region}}"
      register: vprokey_out

    - name: Save private key into file loginkey_vpro.pem
      copy:
        content: "{{vprokey_out.key.private_key}}"
        dest: "./loginkey_vpro.pem"
        mode: 0600
      when: vprokey_out.changed
